a = input('digite algo: ')
print('o tipo primitivo desse valor é ', type(a))
print('só tem espaços? ', a.isspace())
print('é um numero? ', a.isnumeric())
print('é alfabetico? ', a.isalpha())
print('é alfanumerico? ', a.isalnum())
print('esta em maiúscula? ', a.isupper())
print('esta em minuscula? ', a.islower())
print('esta capitalizada? ', a.istitle())
